### ISSUE TITLE
WEASEL is not working anymore

### ISSUE THREAD

**Issue by ChristianSch** [ChristianSch/SFA#3]
```
    java.lang.IllegalArgumentException: feature nodes must be sorted by index in ascending order
        at de.bwaldvogel.liblinear.Linear.train(Linear.java:1735)
        at sfa.classification.WEASELClassifier$2.run(WEASELClassifier.java:309)
```

**Comment by mohataher** [comment]
Hi Christian:

Following up on our discussion on [main repo issue](https://github.com/patrickzib/SFA/issues/3), we need to mature the work on this fork to qualify for a successful pull request.

Based on your discussion with @Patrickzib and myself, I have identified the list of actions to be done.
1. Merge Patrick's latest changes with the master here.
1.  Solve issues in the tests cases fork. 
1. Change library versions to Patrick's recommendations. 
1. Add more test cases and more assertions. 
1. Send pull request to Patrick's main repo.
1. Remove all unnecessary files/folders such as `.settings` from repo and from history as well and update `.gitignore` file.

What do you think? Are there any more suggestions you have here?

**Comment by ChristianSch** [comment]
I agree with your list from the first glance. I'm going to give you both contributor access to my repo so that you can get started when and if you want.

One question though, what do you mean with the library versions? I couldn't find any (or missed) references in the other issue.

**Comment by patrickzib** [comment]
I just had a look at the code. There is a typo in WEASELModel.java:

```
   public int getWordChi(long word) {
      [...]
      if ((index = this.dictChi.indexOf(word)) >= 0) {
        return this.dict.indexGet(index);
      }
      [...]
    }
```

should be:

```
   public int getWordChi(long word) {
      [...]
      if ((index = this.dictChi.indexOf(word)) >= 0) {
        return this.dictChi.indexGet(index);
      }
      [...]
    }
```

this does fix the issue...

**Comment by patrickzib** [comment]
regarding library versions: i had tried hppc 0.8.0 but this doesn't seem to be included in maven-central, yet. so i have backported it to your recommendation of 0.7.2.

**Comment by ChristianSch** [comment]
I see. I'm currently looking into merging your commits. Could take a while as I'm leaving in half an hour. Running tests now, this takes some time as well.

Btw: both of you should have received an invitation to join in this repo, it's hidden in the lower left of the notification page of github: https://github.com/notifications

**Comment by patrickzib** [comment]
Btw: the source directory structure of the tests cases didn't work for me in eclipse,  as the package name didnt reflect the source directory structure.

**Comment by mohataher** [comment]
Will that guide help @patrickzib ? https://stackoverflow.com/questions/8620127/maven-in-eclipse-step-by-step-installation

**Comment by mohataher** [comment]
I have:
1. Added to `gitignore` all unnecessary eclipse and gradle files that are not needed for development.
1. Merged this repo's master with Patrick's master. So we are up to date on this fork.
1. Ran all test cases. Only `SFABulkLoad` is still not passing. Too much IO. Makes me wonder why we need to work with 1,000,000 chunks! Any reason behind that?

**Comment by ChristianSch** [comment]
Nice. But you have overwritten my changes regarding dependency updates if I see correct? Looks like you just merged with `git merge --theirs`, but I can't inspect in detail right now.

**Comment by patrickzib** [comment]
Actually, you are right,  for correctness reasons it is not necessary to use that many chunks. 

(I was working on indexing terabyte sized data that was why I tested larger data sets) 

Thanks for the link. I think an issue is that the classes in package sfa.test have to be in a directory called sfa/test? I.e. SFABulkLoad.java should be in the directory src/test/java/sfa/test...? Or am I mistaking?

**Comment by mohataher** [comment]
Sorry about that Christian. Which file are you referring to?

**Comment by mohataher** [comment]
Patrick, thanks. What would be an appropriate size?

All tests should be in `src/test/java` and in packages matching the same package names of their corresponding class. Ideally, each class in your project needs to have a test class with the same name ending with test. And need to be in the same package name. [Have a look.](https://www.tutorialspoint.com/maven/images/ij_project_structure.jpg)

**Comment by patrickzib** [comment]
Never mind about the test cases. I see it has changed. :)

 (subdirectories within test folder were missing before)

**Comment by patrickzib** [comment]
Oh: 100_000 chunks (or less) should be fine, too :)

**Comment by mohataher** [comment]
@patrickzib Thanks for letting me know. 

I feel we need to separate two concepts. Tests cases and benchmarking/stress testing. They are different and need to be separated. `SFABulkLoad` mixes both and should be separated but that's out of the scope of this issue `#3`. I will get back to you with more details when we sort other issues with more priorities.

**Comment by mohataher** [comment]
Since I didn't hear anything from @ChristianSch , I will make minor fixes. 1) add `Test` at the end of each unit test class to follow Java conventions, 2) put 1M to 10K  and 3) submit a pull request.

**Comment by mohataher** [comment]
Good news, all test cases are passing. 

I updated few test cases and few classes that Patrick updated in the past few days. I feel that now is the right time to send a pull request to the main repo. Just to win some time I will do it now and Patrick can either accept or reject it. 

This issue is closed.

**Comment by patrickzib** [comment]
cool. thank you @mohataher ... 
I have to figure out how to review pull request now :)

**Comment by patrickzib** [comment]
the sad thing is that the history got lost due to the pull request. don't know how this could happen. maybe due to moving the files?

**Comment by mohataher** [comment]
Excellent effort from both sides. Thanks a lot for helping as well, Patrick. 

It's certainly moving and renaming (together) files. You still have track of the changes but it's not followed up in the same repo. I still have few more ideas to make this a high quality library that is industry-ready. ;)

**Comment by ChristianSch** [comment]
Sorry, I'm a bit busy now. Since the test cases seem to work with the newest library versions I might've been mistaken, I just looked at the code. Cheers!
